title: "Website ADA"
tagline: "Applied Data Analysis â€“ EPFL"
description: "Project Website for ADA 2025"
github_username: louistschanz

url: "https://louistschanz.github.io"
baseurl: "/Website_ADA"   # EXACT repo name

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  style: compressed

highlighter: rouge

header_pages:
  - index.md
  - read-me.md
  - preview.md

font-size: small